/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/aumB2933Zi4
 */
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

export function User() {
  return (
    <div className="flex flex-col w-full min-h-screen mt-12">
      <main className="flex-1 overflow-y-auto">
        <div className="grid gap-6 p-4 md:p-6">
          <div className="flex flex-col gap-4">
            <div className="grid gap-2">
              <div className="text-lg font-semibold">个人</div>
              <div className="text-sm leading-none text-gray-500 dark:text-gray-400">
                你的个人信息
              </div>
            </div>
            <Card>
              <CardContent className="grid grid-rows-2 grid-cols-2 grid-flow-row gap-4">
                <div className="font-medium">姓名</div>
                <div className="grid sm:grid-cols-2 gap-2 items-start">
                  张三
                </div>
                <div className="font-medium">姓名</div>
                <div className="grid sm:grid-cols-2 gap-2 items-start">
                  张三
                </div>
              </CardContent>
            </Card>
          </div>
          <div className="flex flex-col gap-4">
            <div className="grid gap-2">
              <div className="text-lg font-semibold">Billing</div>
              <div className="text-sm leading-none text-gray-500 dark:text-gray-400">
                Manage your billing information
              </div>
            </div>
            <Card>
              <CardContent className="grid gap-4 text-sm">
                <div className="grid md:grid-cols-1 gap-4">
                  <div className="font-medium">Card</div>
                  <div className="grid sm:grid-cols-1 gap-2 items-start">
                    <div>**** **** **** 1234</div>
                    <Button size="icon" variant="ghost">
                      <FileEditIcon className="w-4 h-4" />
                      <span className="sr-only">Edit</span>
                    </Button>
                  </div>
                </div>
                <div className="grid md:grid-cols-2 gap-4">
                  <div className="font-medium">Expires</div>
                  <div className="grid sm:grid-cols-1 gap-2 items-start">
                    <div>12/24</div>
                    <Button size="icon" variant="ghost">
                      <FileEditIcon className="w-4 h-4" />
                      <span className="sr-only">Edit</span>
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  );
}

function FileEditIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 13.5V4a2 2 0 0 1 2-2h8.5L20 7.5V20a2 2 0 0 1-2 2h-5.5" />
      <polyline points="14 2 14 8 20 8" />
      <path d="M10.42 12.61a2.1 2.1 0 1 1 2.97 2.97L7.95 21 4 22l.99-3.95 5.43-5.44Z" />
    </svg>
  );
}
